2 CNN: 0.98
1 CNN: 0.9615 epoch 3
1 CNN: 0.9782 epoch 50
ABC: 0.9575 batch 100, lr 0.0001, metrics criterion 'CE', epoch 3
ABC: 0.9671 batch 100, lr 0.0001, metrics criterion 'CE', epoch 6
ABC: 0.9768 epoch 50 kernel_per_pixel 8

In [1]:
import torch
import torchvision
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils.tools import dotdict
from driver.driver import ABC_Driver
torch.cuda.is_available()
torch.cuda.set_device(0)
import atd2022

In [2]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 60
mnist_args.predict.batch_size = 1000

mnist_args.train_epochs= 3
mnist_args.lr = 0.0001
mnist_args.criterion = 'CE'
mnist_args.use_gpu = True

mnist_args.input_channel = 1
mnist_args.input_height = 28
mnist_args.input_width = 28
mnist_args.kernel_size = 9
mnist_args.knpp = 10

In [38]:
atd_args = dotdict()
atd_args.train = dotdict()

atd_args.name = 'atd'
atd_args.train.batch_size = 30
atd_args.predict_len = 1
atd_args.history_len = 2

atd_args.train_epochs= 500
atd_args.lr = 0.01
atd_args.criterion = 'L1'
atd_args.use_gpu = True

atd_args.input_channel = atd_args.history_len
atd_args.input_height = 1
atd_args.input_width = 5200
atd_args.kernel_size = 10
atd_args.knpp = 2

In [39]:
args = atd_args
data = atd2022.io.read_csv()
# data = None
driver = ABC_Driver(args, data)
driver.train()

Use GPU: cuda:None
epoch: 0, train_loss: 185387.02673339844
epoch: 1, train_loss: 67457.7373046875
epoch: 2, train_loss: 53555.68212890625
epoch: 3, train_loss: 28414.289184570312
epoch: 4, train_loss: 16215.845703125
epoch: 5, train_loss: 12908.164916992188
epoch: 6, train_loss: 12592.016845703125
epoch: 7, train_loss: 8057.8001708984375
epoch: 8, train_loss: 6691.250427246094
epoch: 9, train_loss: 5188.834228515625
epoch: 10, train_loss: 4200.933197021484
epoch: 11, train_loss: 3392.992218017578
epoch: 12, train_loss: 2820.3392944335938
epoch: 13, train_loss: 2315.4476470947266
epoch: 14, train_loss: 1966.7245178222656
epoch: 15, train_loss: 1639.0831909179688
epoch: 16, train_loss: 1384.4906311035156
epoch: 17, train_loss: 1155.9023361206055
epoch: 18, train_loss: 1003.4671096801758
epoch: 19, train_loss: 869.5424652099609
epoch: 20, train_loss: 780.389289855957
epoch: 21, train_loss: 679.0180587768555
epoch: 22, train_loss: 629.3713836669922
epoch: 23, train_loss: 554.0561485290527

epoch: 198, train_loss: 58.19011211395264
epoch: 199, train_loss: 55.85291576385498
epoch: 200, train_loss: 61.70358943939209
epoch: 201, train_loss: 53.60595703125
epoch: 202, train_loss: 54.482884883880615
epoch: 203, train_loss: 54.13412952423096
epoch: 204, train_loss: 62.79181146621704
epoch: 205, train_loss: 55.779242515563965
epoch: 206, train_loss: 52.42071771621704
epoch: 207, train_loss: 55.63544034957886
epoch: 208, train_loss: 57.88225698471069
epoch: 209, train_loss: 58.23936605453491
epoch: 210, train_loss: 53.41038131713867
epoch: 211, train_loss: 58.87883758544922
epoch: 212, train_loss: 53.51545763015747
epoch: 213, train_loss: 54.86611604690552
epoch: 214, train_loss: 54.57124662399292
epoch: 215, train_loss: 60.46696996688843
epoch: 216, train_loss: 51.41013145446777
epoch: 217, train_loss: 52.64973449707031
epoch: 218, train_loss: 54.67036581039429
epoch: 219, train_loss: 52.71439027786255
epoch: 220, train_loss: 53.27168130874634
epoch: 221, train_loss: 54.76443481

epoch: 394, train_loss: 39.44849920272827
epoch: 395, train_loss: 37.64045524597168
epoch: 396, train_loss: 40.18035840988159
epoch: 397, train_loss: 35.79669451713562
epoch: 398, train_loss: 37.38870668411255
epoch: 399, train_loss: 37.04893779754639
epoch: 400, train_loss: 39.28644680976868
epoch: 401, train_loss: 35.92985939979553
epoch: 402, train_loss: 37.30841112136841
epoch: 403, train_loss: 37.09222912788391
epoch: 404, train_loss: 37.94956731796265
epoch: 405, train_loss: 38.821826457977295
epoch: 406, train_loss: 34.67558836936951
epoch: 407, train_loss: 37.043763160705566
epoch: 408, train_loss: 34.40589618682861
epoch: 409, train_loss: 36.538894176483154
epoch: 410, train_loss: 34.860113859176636
epoch: 411, train_loss: 42.15435600280762
epoch: 412, train_loss: 35.548370122909546
epoch: 413, train_loss: 35.361693382263184
epoch: 414, train_loss: 33.5046489238739
epoch: 415, train_loss: 38.984294414520264
epoch: 416, train_loss: 36.06252956390381
epoch: 417, train_loss: 37.0

In [44]:
train_pred = driver.predict(driver.data_loader.train).to(float).round()
train_pred

tensor([[[[-40.,   1., -41.,  ..., -11., -69., -29.]]],


        [[[ 14., -36., -15.,  ...,  23.,  32.,  30.]]],


        [[[  7., -26.,  40.,  ...,  30.,  -3.,  39.]]],


        ...,


        [[[ 13.,   0., -23.,  ..., 116., 185.,  57.]]],


        [[[ 25., -34., -35.,  ...,  42., 140.,  62.]]],


        [[[  0., -33., -12.,  ..., 143., 135.,  55.]]]], dtype=torch.float64)

In [41]:
pred = driver.predict().to(float)
pred

tensor([[[[-11.0284,  -0.2645,  26.7892,  ..., 162.1727,  83.6228,  42.1392]]]],
       dtype=torch.float64)

In [23]:
pred = driver.predict().to(float)
pred

tensor([[[[  7.7031,   2.9904,   3.4786,  ...,  80.0183, 205.7635,   0.0000]],

         [[ 10.1797,   1.5562,   3.0605,  ...,  76.9034, 209.3571,   0.0000]],

         [[  7.8379,   2.6050,   3.5921,  ...,  77.9101, 224.6351,   0.0000]],

         [[  8.1780,   2.4698,   3.5343,  ...,  75.4261, 224.9489,   0.0000]]]],
       dtype=torch.float64)

In [27]:
data.mean()

Region  Event
AA      01        10.474419
        02         4.139535
        03         7.246512
        04        24.525581
        05         5.079070
                    ...    
ZI      16        47.562791
        17       268.395349
        18        93.986047
        19       204.846512
        20         1.320930
Length: 5200, dtype: float64

In [6]:
driver.metric()

0.9584