2 CNN: 0.98
1 CNN: 0.9615 epoch 3
1 CNN: 0.9782 epoch 50
ABC: 0.9575 batch 100, lr 0.0001, metrics criterion 'CE', epoch 3
ABC: 0.9671 batch 100, lr 0.0001, metrics criterion 'CE', epoch 6
ABC: 0.9768 epoch 50 kernel_per_pixel 8

In [1]:
import torch
import torchvision
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils.tools import dotdict
from driver.driver import ABC_Driver
torch.cuda.is_available()
torch.cuda.set_device(0)
import atd2022

In [2]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 60
mnist_args.predict.batch_size = 100

mnist_args.train_epochs= 3
mnist_args.lr = 0.0001
mnist_args.criterion = 'CE'
mnist_args.use_gpu = True

mnist_args.input_channel = 1
mnist_args.input_height = 28
mnist_args.input_width = 28
mnist_args.kernel_size = 9
mnist_args.knpp = 10
mnist_args.knpp2 = 20

In [7]:
atd_args = dotdict()
atd_args.train = dotdict()

atd_args.name = 'atd'
atd_args.train.batch_size = 30
atd_args.predict_len = 1
atd_args.history_len = 5

atd_args.train_epochs= 100
atd_args.lr = 0.001
atd_args.criterion = 'L1'
atd_args.use_gpu = True

atd_args.input_channel = atd_args.history_len
atd_args.input_height = 1
atd_args.input_width = 5200
atd_args.kernel_size = 6
atd_args.knpp = 6
atd_args.knpp2 = atd_args.predict_len

In [8]:
args = atd_args
data = atd2022.io.read_csv()
# data = None
driver = ABC_Driver(args, data)
driver.train()

Use GPU: cuda:None
epoch: 0, train_loss: 1677.9812273297991
epoch: 1, train_loss: 713.2244698660714
epoch: 2, train_loss: 490.13682774135043
epoch: 3, train_loss: 330.42532784598217
epoch: 4, train_loss: 259.0156555175781
epoch: 5, train_loss: 195.42953055245536
epoch: 6, train_loss: 168.37197875976562
epoch: 7, train_loss: 140.175416128976
epoch: 8, train_loss: 128.48887852260046
epoch: 9, train_loss: 115.18753269740513
epoch: 10, train_loss: 107.58632550920758
epoch: 11, train_loss: 102.3252944946289
epoch: 12, train_loss: 99.1250501360212
epoch: 13, train_loss: 96.6686771937779
epoch: 14, train_loss: 95.21415383475167
epoch: 15, train_loss: 93.94769941057477
epoch: 16, train_loss: 92.8110842023577
epoch: 17, train_loss: 91.53690011160714
epoch: 18, train_loss: 90.53574044363839
epoch: 19, train_loss: 88.89382825578961
epoch: 20, train_loss: 87.39259120396206
epoch: 21, train_loss: 86.03233228410993
epoch: 22, train_loss: 84.85106004987445
epoch: 23, train_loss: 84.01819501604352
epo

In [ ]:
# driver.metric()

In [9]:
train_pred = driver.predict(driver.data_loader.train).to(float).round()
train_pred

tensor([[[[ 61.,  58., -31.,  ...,  52., 127.,   4.]]],


        [[[ 61.,  47., -42.,  ...,  21., 131., -12.]]],


        [[[ 41.,  24., -17.,  ...,  38., 120.,   5.]]],


        ...,


        [[[ 58.,  50., -12.,  ...,  84., 213.,  24.]]],


        [[[ 32.,  55., -16.,  ...,  53., 210.,  24.]]],


        [[[ 58.,  51., -32.,  ...,  97., 219.,  16.]]]], dtype=torch.float64)

In [10]:
pred = driver.predict().to(float)
pred

tensor([[[[ 46.9483,  57.5578,  -9.9931,  ...,  97.7333, 254.3347,   6.7233]]]],
       dtype=torch.float64)

In [ ]:
data.mean()

In [9]:
a = torch.tensor([[1,2],[3,4]])

In [11]:
torch.concat([a,a],axis=1)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])