CNN: 0.98
ABC:

In [1]:
import torch
import torchvision
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils.tools import dotdict
from driver.driver import ABC_Driver
torch.cuda.is_available()
torch.cuda.set_device(1)

/scratch/wzong/anaconda3/envs/atd2022/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [2]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 100
mnist_args.predict.batch_size = 1000

In [3]:
args = dotdict()
args.data = mnist_args

args.train_epochs= 50
args.lr = 0.00008
args.criterion = 'CE'
args.use_gpu = True

In [4]:
driver = ABC_Driver(args)

Use GPU: cuda:None


In [10]:
driver.model.state_dict()

OrderedDict([('ABC_2D.weights',
              tensor([[[ 0.4218,  0.3002,  0.6538,  ...,  1.3585, -0.4829, -0.2831],
                       [ 0.0428,  0.9148, -1.5040,  ..., -0.5533,  0.0680, -0.3943],
                       [ 0.9771,  1.2894, -0.1461,  ..., -0.3790, -1.6897,  0.7358],
                       [ 0.4503,  0.0878, -0.1522,  ...,  1.1652, -1.4519,  0.4280],
                       [ 0.1916, -1.2229,  1.7847,  ...,  1.7269, -1.2191,  1.1335],
                       [ 0.3579, -0.3335, -1.0616,  ...,  1.6197, -0.6532,  0.1870]],
              
                      [[ 0.0663,  0.1367, -2.2416,  ..., -1.6642, -0.4024, -0.4639],
                       [ 0.9143,  1.0498, -0.4036,  ..., -0.4032, -0.2414, -0.0034],
                       [-1.5426, -1.2596,  0.4973,  ..., -0.5816,  0.0848,  0.9098],
                       [-1.7658,  0.4488,  0.0207,  ..., -1.1954, -2.2408, -0.0970],
                       [-0.7729,  0.1407,  0.8280,  ...,  0.9302, -0.1723,  0.0836],
                 

In [11]:
driver.train()

epoch: 6, train_loss: 1.5023006985584895
epoch: 7, train_loss: 1.498948969244957
epoch: 8, train_loss: 1.4962995237112044
epoch: 9, train_loss: 1.4938413800795873
epoch: 10, train_loss: 1.4919223195314408
epoch: 11, train_loss: 1.4900527968009314
epoch: 12, train_loss: 1.488496835430463
epoch: 13, train_loss: 1.486982323129972
epoch: 14, train_loss: 1.4855632835626602
epoch: 15, train_loss: 1.4845266052087147
epoch: 16, train_loss: 1.4832628407080968
epoch: 17, train_loss: 1.4823627283175786
epoch: 18, train_loss: 1.4815193309386572
epoch: 19, train_loss: 1.4808485080798468
epoch: 20, train_loss: 1.4800190323591231
epoch: 21, train_loss: 1.479402735431989
epoch: 22, train_loss: 1.478859665195147
epoch: 23, train_loss: 1.478143733938535
epoch: 24, train_loss: 1.477527274688085
epoch: 25, train_loss: 1.4769593713680904
epoch: 26, train_loss: 1.4764393252134322
epoch: 27, train_loss: 1.475951943596204
epoch: 28, train_loss: 1.4755880930026373
epoch: 29, train_loss: 1.475134570201238
epoch

In [12]:
driver.metric()

0.9768

In [13]:
driver.model.state_dict()

OrderedDict([('ABC_2D.weights',
              tensor([[[ 0.4218,  0.3002,  0.6538,  ...,  1.3585, -0.4829, -0.2831],
                       [ 0.0428,  0.9148, -1.5040,  ..., -0.5533,  0.0680, -0.3943],
                       [ 0.9771,  1.2894, -0.1461,  ..., -0.3790, -1.6897,  0.7358],
                       [ 0.4761,  0.1135, -0.1265,  ...,  1.1909, -1.4262,  0.4537],
                       [ 0.1916, -1.2229,  1.7847,  ...,  1.7269, -1.2191,  1.1335],
                       [ 0.3579, -0.3335, -1.0616,  ...,  1.6197, -0.6532,  0.1870]],
              
                      [[ 0.0945,  0.1648, -2.2135,  ..., -1.6361, -0.3742, -0.4358],
                       [ 0.9143,  1.0498, -0.4036,  ..., -0.4032, -0.2414, -0.0034],
                       [-1.5146, -1.2316,  0.5254,  ..., -0.5536,  0.1129,  0.9378],
                       [-1.7448,  0.4697,  0.0416,  ..., -1.1745, -2.2198, -0.0761],
                       [-0.7729,  0.1407,  0.8280,  ...,  0.9302, -0.1723,  0.0836],
                 

In [22]:
train_data = torchvision.datasets.MNIST('../../data/ABC/mnist', train=False, download=True,
                                                  transform=torchvision.transforms.Compose([torchvision.transforms.ToTensor(),
                                                            torchvision.transforms.Normalize((0.1307,), (0.3081,))]))

In [23]:
train_data.

Dataset MNIST
    Number of datapoints: 10000
    Root location: ../../data/ABC/mnist
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [20]:
a = torch.tensor([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])

In [21]:
torch.matmul(a,a)

tensor([[[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]]])

In [14]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 100
mnist_args.predict.batch_size = 1000

In [5]:
driver.train()

epoch: 0, train_loss: 1.8092176419496537
epoch: 1, train_loss: 1.5854661240180334
epoch: 2, train_loss: 1.5594474685192108
epoch: 3, train_loss: 1.547036578655243
epoch: 4, train_loss: 1.5385117679834366
epoch: 5, train_loss: 1.532321839928627
epoch: 6, train_loss: 1.527201450864474
epoch: 7, train_loss: 1.5227444046735763
epoch: 8, train_loss: 1.5188205428918202
epoch: 9, train_loss: 1.5152481007575989
epoch: 10, train_loss: 1.5122010159492492
epoch: 11, train_loss: 1.5093879654010136
epoch: 12, train_loss: 1.5068205038706461
epoch: 13, train_loss: 1.504511877099673
epoch: 14, train_loss: 1.5022801474730174
epoch: 15, train_loss: 1.5006628227233887
epoch: 16, train_loss: 1.4987579685449601
epoch: 17, train_loss: 1.4970314226547876
epoch: 18, train_loss: 1.4954067504405975
epoch: 19, train_loss: 1.4939528038104375
epoch: 20, train_loss: 1.492574091553688
epoch: 21, train_loss: 1.491297993262609
epoch: 22, train_loss: 1.4901642004648845
epoch: 23, train_loss: 1.488807551264763
epoch: 24

In [6]:
driver.metric()

0.9782