CNN: 0.98
ABC:

In [1]:
import torch
import torchvision
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils.tools import dotdict
from driver.driver import ABC_Driver
torch.cuda.is_available()
torch.cuda.set_device(2)
import atd2022

/scratch/wzong/anaconda3/envs/atd2022/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [2]:
truth = atd2022.io.read_csv()

In [3]:
args = dotdict()

args.train_epochs= 200
args.lr = 0.01
args.criterion = 'L1'
args.use_gpu = True

args.history_len = 30
args.input_channel = args.history_len

args.predict_len = 4
args.input_height = 1
args.input_width = 5200
args.kernel_size = 1
args.knpp = 6
args.batch_size = 20
# args.df = truth



In [4]:
driver = ABC_Driver(args, df = truth)

Use GPU: cuda:None


In [5]:
# driver.model.state_dict()

In [6]:
driver.train()

label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([18, 4, 1, 5200])
out:  torch.Size([18, 4, 1, 5200])
epoch: 0, train_loss: 782880.8055555555
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
out:  torch.Size([20, 4, 1, 5200])
label: torch.Size([20, 4, 1, 5200])
o

KeyboardInterrupt: 

In [ ]:
test = driver.predict()

In [11]:
test

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.]]]])

In [34]:
driver.model.state_dict()

OrderedDict([('ABC_2D.weights',
              tensor([[[-0.7286,  0.8767,  0.0780,  ..., -1.3279, -2.2808,  0.4637],
                       [-0.1018, -0.1547,  0.8325,  ...,  1.1137, -1.0467, -0.9357],
                       [ 0.5119, -0.6160, -1.1352,  ...,  0.5411,  0.5418, -0.3512],
                       [ 1.5461, -1.4093, -0.6760,  ...,  0.0707, -1.5224,  0.9648],
                       [ 0.2135, -0.1838,  0.9960,  ...,  0.6897,  1.1498, -0.5737],
                       [-1.5255, -0.6626, -0.5416,  ...,  1.5347, -0.7379, -0.7458]],
              
                      [[-0.7651,  0.3481,  1.4335,  ...,  0.6536, -0.2754, -1.2215],
                       [ 0.7908,  0.8910,  0.7593,  ..., -1.0810,  0.7118,  0.0436],
                       [-1.1786, -1.3707, -1.4836,  ...,  0.3900, -0.1641,  0.4137],
                       [-0.1428, -2.3256, -0.3764,  ...,  0.3292, -0.7050, -0.0718],
                       [ 1.6733,  1.1365, -0.9140,  ...,  0.2969,  0.4022, -0.4778],
                 

In [22]:
train_data = torchvision.datasets.MNIST('../../data/ABC/mnist', train=False, download=True,
                                                  transform=torchvision.transforms.Compose([torchvision.transforms.ToTensor(),
                                                            torchvision.transforms.Normalize((0.1307,), (0.3081,))]))

In [23]:
train_data.

Dataset MNIST
    Number of datapoints: 10000
    Root location: ../../data/ABC/mnist
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [20]:
a = torch.tensor([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])

In [21]:
torch.matmul(a,a)

tensor([[[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]]])

In [14]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 100
mnist_args.predict.batch_size = 1000

In [5]:
driver.train()

epoch: 0, train_loss: 1.8092176419496537
epoch: 1, train_loss: 1.5854661240180334
epoch: 2, train_loss: 1.5594474685192108
epoch: 3, train_loss: 1.547036578655243
epoch: 4, train_loss: 1.5385117679834366
epoch: 5, train_loss: 1.532321839928627
epoch: 6, train_loss: 1.527201450864474
epoch: 7, train_loss: 1.5227444046735763
epoch: 8, train_loss: 1.5188205428918202
epoch: 9, train_loss: 1.5152481007575989
epoch: 10, train_loss: 1.5122010159492492
epoch: 11, train_loss: 1.5093879654010136
epoch: 12, train_loss: 1.5068205038706461
epoch: 13, train_loss: 1.504511877099673
epoch: 14, train_loss: 1.5022801474730174
epoch: 15, train_loss: 1.5006628227233887
epoch: 16, train_loss: 1.4987579685449601
epoch: 17, train_loss: 1.4970314226547876
epoch: 18, train_loss: 1.4954067504405975
epoch: 19, train_loss: 1.4939528038104375
epoch: 20, train_loss: 1.492574091553688
epoch: 21, train_loss: 1.491297993262609
epoch: 22, train_loss: 1.4901642004648845
epoch: 23, train_loss: 1.488807551264763
epoch: 24

In [6]:
driver.metric()

0.9782

In [15]:
test = torch.randn(3,10)

In [16]:
test.shape

torch.Size([3, 10])

In [17]:
a = test.reshape(-1)

In [18]:
a.shape

torch.Size([30])