CNN: 0.98
ABC:

In [2]:
import torch
import torchvision
import torch.nn.functional as F
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from utils.tools import dotdict
from driver.driver import ABC_Driver
torch.cuda.is_available()
torch.cuda.set_device(0)

/scratch/wzong/anaconda3/envs/atd2022/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [3]:
mnist_args = dotdict()
mnist_args.train = dotdict()
mnist_args.predict = dotdict()

mnist_args.name = 'mnist'
mnist_args.train.batch_size = 100
mnist_args.predict.batch_size = 1000

In [10]:
args = dotdict()
args.data = mnist_args

args.train_epochs= 3
args.lr = 0.001
args.criterion = 'CE'
args.use_gpu = True

In [11]:
driver = ABC_Driver(args)

Use GPU: cuda:None


In [12]:
driver.model.state_dict()

OrderedDict([('ABC_2D.weights',
              tensor([[[-1.5218,  1.0246, -0.0488,  ...,  0.8863,  0.3041, -2.3695],
                       [-1.2885,  0.8352, -0.8133,  ...,  0.6128,  0.2022, -0.7438],
                       [-0.2829,  1.9803,  0.8498,  ..., -0.3721,  0.4245, -1.0244],
                       ...,
                       [-0.1197,  0.6784,  0.7795,  ...,  1.0237, -1.3710,  0.6500],
                       [-1.3420,  0.9878,  0.5070,  ..., -0.4545,  0.8825, -0.6211],
                       [ 1.9944,  0.2765,  0.6320,  ...,  0.8203,  0.8049,  0.1274]],
              
                      [[ 0.8024,  0.2453, -0.9998,  ..., -0.6848, -0.4294, -0.2490],
                       [ 0.4944, -0.5614,  1.0087,  ..., -1.3115, -0.3432, -0.1588],
                       [-1.3730, -0.9328,  1.1380,  ...,  0.8215, -0.3538,  0.0715],
                       ...,
                       [-0.2879,  0.0436, -0.9746,  ...,  0.2788,  0.1342, -0.3422],
                       [-0.3960, -0.2110, -1.6

In [ ]:
driver.train()

In [8]:
driver.metric()

0.108

In [9]:
driver.model.state_dict()

OrderedDict([('ABC_2D.weights',
              tensor([[[-1.2559,  0.7109, -0.3933,  ..., -0.1976,  0.3286, -0.2753],
                       [ 0.1714, -0.2779,  0.5750,  ..., -1.4057, -0.3527,  1.2468],
                       [ 0.5447, -1.1861,  0.6824,  ...,  0.7203, -0.5217, -0.4538],
                       ...,
                       [-0.0616,  1.1719,  0.9073,  ..., -1.0860, -1.2161, -0.1169],
                       [-1.4456,  0.9580, -1.8438,  ..., -1.2719, -0.1065,  0.7902],
                       [-1.3809, -0.5790, -0.6130,  ...,  1.0997,  0.2957,  0.3161]],
              
                      [[-0.9749, -0.8653, -0.0832,  ...,  0.1448,  0.9039,  0.0789],
                       [-1.7358, -0.5185,  1.2372,  ..., -1.1404,  0.4607,  0.3953],
                       [-1.4071,  0.3923,  1.2142,  ..., -2.0839,  1.6465, -1.0257],
                       ...,
                       [-0.1976,  0.3589, -0.5279,  ..., -1.7368, -1.0413, -0.9324],
                       [ 1.3106,  0.7110, -1.7

In [22]:
train_data = torchvision.datasets.MNIST('../../data/ABC/mnist', train=False, download=True,
                                                  transform=torchvision.transforms.Compose([torchvision.transforms.ToTensor(),
                                                            torchvision.transforms.Normalize((0.1307,), (0.3081,))]))

In [23]:
train_data.

Dataset MNIST
    Number of datapoints: 10000
    Root location: ../../data/ABC/mnist
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.1307,), std=(0.3081,))
           )

In [20]:
a = torch.tensor([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]])

In [21]:
torch.matmul(a,a)

tensor([[[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]],

        [[ 7, 10],
         [15, 22]]])